---
title: "NHANES Snapshot Looking at Oral Health, Fasting Glucose Levels, and BMI"
format: 
  dashboard:
    nav-buttons: [github]
    github: https://github.com/vpastrana7/vpastrana7.github.io
logo: images/logo.png
theme: [sandstone, theme/custom.scss]
fig-width: 10
fig-asp: 0.3
params:
  month: "December"
  year: "2024"
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-packages
#| message: false

library(janitor)
library(naniar)
library(patchwork)
library(xfun)
library(Epi)
library(Hmisc)
library(nhanesA)
library(foreign)

library(easystats)
library(broom)
library(rstanarm)
library(tidyverse)
theme_set(theme_minimal(base_size = 24, base_family = "sans"))
```

```{r}
#| label: load-data
#| message: false
#| results: hide

#import all data from downloaded files

demo_raw <- read.xport("P_DEMO.xpt")
oral_health_raw <- read.xport("P_OHXDEN.xpt")
fast_glucose <- read.xport("P_GLU.xpt")
body_mx <- read.xport("P_BMX.xpt")

#make dataframes with variables I want

NEW <- left_join(demo_raw, oral_health_raw, by = "SEQN")
NEW2 <- left_join(NEW, body_mx, by = "SEQN")
final_raw <- left_join(NEW2, fast_glucose, by = "SEQN")
final_1 <- final_raw %>% filter(RIDSTATR == 2, RIDAGEYR < 80, RIDAGEYR > 20) %>% select(SEQN, OHXRCAR, BMXBMI, LBXGLU)
summary(final_1)
```

# BMI + Caries

## Column {width="50%"}

```{r}
#| label: BMI + Caries
#| title: Visualization of BMI for Patients with Caries

#choose data to look at normality

final_1 %>% filter(OHXRCAR == 1) %>% #saw that there was right skewing with no transformation
  ggplot(aes(sample = BMXBMI)) +
  geom_qq() + geom_qq_line() +
  labs(x= "Patient BMI",
       title = "Normality of BMI",
       subtitle = "Patients with Root Caries")

final_BMIanaly <- final_1 %>% mutate(logBMXBMI = log(BMXBMI)) %>% select(SEQN, OHXRCAR, logBMXBMI)

final_BMIanaly %>% filter(OHXRCAR == 1) %>% #distribution looks much better
  ggplot(aes(sample = logBMXBMI)) +
  geom_qq() + geom_qq_line() +
  labs(x= "Patient log(BMI)",
       title = "Normality of Transformed BMI",
       subtitle = "Patients with Root Caries")

ggplot(data = final_BMIanaly, aes(x = logBMXBMI)) + #histogram also looks good!
geom_histogram(bins = 20, fill = "coral", col = "ivory") +
labs(title = "BMI Spread in Patients with Root Caries")


```


```{r}
#| title: Visualization of BMI for Patients with No Caries

#choose data to look at normality

final_1 %>% filter(OHXRCAR == 2) %>% #saw that there was right skewing with no transformation
  ggplot(aes(sample = BMXBMI)) +
  geom_qq() + geom_qq_line() +
  labs(x= "Patient BMI",
       title = "Normality of BMI",
       subtitle = "Patients with No Root Caries")

final_BMIanaly <- final_1 %>% mutate(logBMXBMI = log(BMXBMI)) %>% select(SEQN, OHXRCAR, logBMXBMI)
final_BMIanaly_nocarie <- final_BMIanaly <- final_1 %>% filter(OHXRCAR == 2) %>% mutate(logBMXBMI = log(BMXBMI)) %>% select(SEQN, OHXRCAR, logBMXBMI)

final_BMIanaly %>% filter(OHXRCAR == 2) %>% #distribution looks much better
  ggplot(aes(sample = logBMXBMI)) +
  geom_qq() + geom_qq_line() +
  labs(x= "Patient log(BMI)",
       title = "Normality of Transformed BMI",
       subtitle = "Patients with No Root Caries")

ggplot(data = final_BMIanaly_nocarie, aes(x = logBMXBMI)) + #histogram also looks good!
geom_histogram(bins = 20, fill = "coral", col = "ivory") +
labs(title = "BMI Spread in Patients with No Root Caries")

```



# Caries + Fasting Glucose

## Column {width="60%"}

```{r}
#| title: Visualization of Fasting Blood Glucose for Patients with Caries

final_1 %>% filter(OHXRCAR == 1) %>% #saw that there was MASSIVE right skewing with no transformation
  ggplot(aes(sample = LBXGLU)) +
  geom_qq() + geom_qq_line() +
  labs(x= "Patient Glucose",
       title = "Normality of Fasting Glucose",
       subtitle = "Patients with Root Caries")

final_GLUanaly <- final_1 %>% mutate(logLBXGLU = log10(LBXGLU)) %>% select(SEQN, OHXRCAR, logLBXGLU)

final_GLUanaly %>% filter(OHXRCAR == 1) %>% #distribution looks much better
  ggplot(aes(sample = logLBXGLU)) +
  geom_qq() + geom_qq_line() +
  labs(x= "Patient log(GLU)",
       title = "Normality of Transformed Glucose Levels",
       subtitle = "Patients with Root Caries")

ggplot(data = final_GLUanaly, aes(x = logLBXGLU)) + #histogram also looks good!
geom_histogram(bins = 20, fill = "coral", col = "ivory") +
labs(title = "Fasting Glucose Spread in Patients with Root Caries")

final_GLUanaly %>% filter(OHXRCAR == 1) %>%
  ggplot(data = ., aes(x = logLBXGLU, y = OHXRCAR)) +
geom_violin(aes(fill = logLBXGLU)) +
geom_boxplot(width = 0.3, outlier.size = 4) + coord_flip() +
guides(fill = "none") +
labs(x = "Group")

outliers_glu <- boxplot(final_GLUanaly$logLBXGLU, plot=FALSE)$out # remove outliers from glucose data
x_glu <- final_GLUanaly
x_glu_out <- x_glu[-which(x_glu$logLBXGLU %in% outliers_glu),]

x_glu_out %>% filter(OHXRCAR == 1) %>% # much better after removing outliers
  ggplot(data = ., aes(x = logLBXGLU, y = OHXRCAR)) +
geom_violin(aes(fill = logLBXGLU)) +
geom_boxplot(width = 0.3, outlier.size = 4) + coord_flip()



```


```{r}
#| title: Visualization of Fasting Blood Glucose for Patients with No Caries

final_1 %>% filter(OHXRCAR == 2) %>% #saw that there was MASSIVE right skewing with no transformation
  ggplot(aes(sample = LBXGLU)) +
  geom_qq() + geom_qq_line() +
  labs(x= "Patient Glucose",
       title = "Normality of Fasting Glucose",
       subtitle = "Patients with Root Caries")

final_GLUanaly <- final_1 %>% mutate(logLBXGLU = log10(LBXGLU)) %>% select(SEQN, OHXRCAR, logLBXGLU)

final_GLUanaly %>% filter(OHXRCAR == 2) %>% #distribution looks a little better (values are closer)
  ggplot(aes(sample = logLBXGLU)) +
  geom_qq() + geom_qq_line() +
  labs(x= "Patient log(GLU)",
       title = "Normality of Transformed Glucose Levels",
       subtitle = "Patients with Root Caries")

final_GLUanaly_nocaries <- final_GLUanaly %>% filter(OHXRCAR == 2)

ggplot(data = final_GLUanaly_nocaries, aes(x = logLBXGLU)) + #histogram looks a little better!
geom_histogram(bins = 20, fill = "coral", col = "ivory") +
labs(title = "Fasting Glucose Spread in Patients with Root Caries")

final_GLUanaly_nocaries %>% filter(OHXRCAR == 2) %>% #a ton of outliers seen
  ggplot(data = ., aes(x = logLBXGLU, y = OHXRCAR)) +
geom_violin(aes(fill = logLBXGLU)) +
geom_boxplot(width = 0.3, outlier.size = 4) + coord_flip() +
guides(fill = "none") +
labs(x = "Group")

outliers_glu <- boxplot(final_GLUanaly_nocaries$logLBXGLU, plot=FALSE)$out # remove outliers from glucose data
x_glu_nocaries <- final_GLUanaly_nocaries
x_glu_out_nocaries <- x_glu[-which(x_glu$logLBXGLU %in% outliers_glu),]

x_glu_out %>% filter(OHXRCAR == 2) %>% # much better after removing many outliers
  ggplot(data = ., aes(x = logLBXGLU, y = OHXRCAR)) +
geom_violin(aes(fill = logLBXGLU)) +
geom_boxplot(width = 0.3, outlier.size = 4) + coord_flip()
```

# Caries BMI + Fasting Glucose - Linear Regression

### Row {height="40%"}
```{r}
#| title: Linear Regression for Patients with caries (BMI v Fasting Glucose)
#| fig-height: 7
final_GLU_BMI <- left_join(x_glu_out, final_BMIanaly, by = "SEQN")
final_GLU_BMI_caries <- final_GLU_BMI %>% filter(OHXRCAR.x == 1)

carie_lm_BMI_GLU <- lm(logBMXBMI ~ logLBXGLU, data = final_GLU_BMI)

carie_lm_BMI_GLU_perf <- model_performance(carie_lm_BMI_GLU)
print(carie_lm_BMI_GLU_perf)

check_model(carie_lm_BMI_GLU, plot = FALSE)

# even after the transformations and the removal of outliers this linear model is still very poor
# however, I am still pleased with the transformations I achieved in order to produce a normally
# distributed data set
```

### Row {height="40%"}
```{r}
#| title: Linear Regression for Patients with No Caries (BMI v Fasting Glucose)
#| fig-height: 9
final_GLU_BMI <- left_join(x_glu_out_nocaries, final_BMIanaly_nocarie, by = "SEQN")
final_GLU_BMI_nocaries <- final_GLU_BMI %>% filter(OHXRCAR.x == 2)

No_carie_lm_BMI_GLU <- lm(logBMXBMI ~ logLBXGLU, data = final_GLU_BMI_nocaries)

nocarie_lm_BMI_GLU_perf <- model_performance(No_carie_lm_BMI_GLU)
print(nocarie_lm_BMI_GLU_perf)

#check_model(No_carie_lm_BMI_GLU, plot = FALSE)

# even after the transformations and the removal of outliers this linear model is still very poor
# however, I am still pleased with the transformations I achieved in order to produce a normally
# distributed data set

# The values may just be too small to properly make a model for these datasets after the log transformation
```


# Fasting Glucose + BMI

```{r}
#| title: Splitting Fasting Glucose Levels Dependent on BMI, not caries. Split into a Low and High BMI group to try and predict fasting glucose levels. 
#| fig-height: 9

final_1 %>% filter(complete.cases(BMXBMI)) %>%
  summarise(q40 = quantile(BMXBMI, c(0.4)),
            q60 = quantile(BMXBMI, c(0.6)))

BMI_grplow <- final_1 %>% filter(BMXBMI <= 27.4)
BMI_grphigh <- final_1 %>% filter(BMXBMI >= 30.7)

BMI_low_lm <- lm(LBXGLU ~ BMXBMI, data = BMI_grplow)
BMI_high_lm <- lm(LBXGLU ~ BMXBMI, data = BMI_grphigh)


BMI_low_lm_perf <- model_performance(BMI_low_lm)
print(BMI_low_lm_perf)
BMI_high_lm_perf <- model_performance(BMI_high_lm)
print(BMI_high_lm_perf)

set.seed(77)
bootstrap_low <- Hmisc::smean.cl.boot(BMI_grplow$LBXGLU, conf.int = 0.95)
bootstrap_low
bootstrap_high <- Hmisc::smean.cl.boot(BMI_grphigh$LBXGLU, conf.int = 0.95)
bootstrap_high

#these bootstrap tests show that there is a potential relation between the lower 40% of BMI values are only prediabetic at most while the top 40% of BMI values still suggests prediabetes, but much closer to the cutoff for diabetes (126 mg/dL) -> could suggest these patients need closer monitoring

```



```{r}
#| title: Checking Regression Models (BMI v Fasting Glucose)
#| results: hide
check_model(BMI_low_lm)
```

```{r}
#| title: Checking Regression Models (BMI v Fasting Glucose)
#| results: hide
check_model(BMI_high_lm)
```

# 2x2 Table - Diabetes and Obesity

```{r}
#| results: hide


final_1 %>% count(LBXGLU > 125 , BMXBMI > 30) # patients with diabetes and obese
final_1 %>% count(LBXGLU < 125 , BMXBMI > 30) # patients with no diabetes and obese
final_1 %>% count(LBXGLU > 125 , BMXBMI < 24.9) # patients with diabetes and normal BMI
final_1 %>% count(LBXGLU < 125, BMXBMI < 24.9) # patients with no diabetes and normal BMI
```


```{r}
#| title: 2x2 Table
diabetesvobesity <- matrix(c(336, 225, 1180, 1865), nrow = 2, byrow = TRUE)
dimnames(diabetesvobesity) <- list(c("Diabetes", "No Diabetes"), c("Obesity", "No Obesity"))
twoby2(diabetesvobesity)
```


